### PR TITLE
Update COC reporting email

### PR DESCRIPTION
**Pull request by joshmoore**
Replace the gmail account with a google group that can have a wider membership.

### CODE REVIEW

**Review by jhamman — APPROVED** [review]
for reference, @joshmoore - who has access to this group today?

**Comment by joshmoore** [comment]
Currently it forwards to the steering council. For clarity, I'll say as much or alternatively we just use the ZSC group for the moment until a COC group can be decided on.

**Comment by jhamman** [comment]
👍The steering council is a reasonable choice. I suggest adding that to the doc then.

**Comment by joshmoore** [comment]
Merging with @jhamman's :+1: since something we can actually read is better than nothing. Further suggestions are *very* welcome, though.

**Pull request merged**
