### PR TITLE
Health files

### PR DESCRIPTION
**Pull request by joshmoore**
See:
 - https://github.blog/changelog/2019-02-21-organization-wide-community-health-files/
 - https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file
 - https://github.com/zarr-developers/governance/issues/3

### CODE REVIEW

**Comment by alimanfoo** [comment]
Hi @joshmoore, this looks good although we probably need a way to deal with different sub-projects having different contributing guides. E.g., the zarr-python project will have different contributing information from zarr-specs. Maybe just a note to this effect is good enough, and then links through to contributing guides within specific sub-projects where they exist?

**Comment by joshmoore** [comment]
I'm _pretty_ sure that this will work as a default for an repository that doesn't have one defined, at least for the reverse use case: user opens a PR gets a reminder to look at the contributing guide, etc. Happy to update the README here to point at all other instances.

**Comment by alimanfoo** [comment]
> I'm _pretty_ sure that this will work as a default for an repository that doesn't have one defined, at least for the reverse use case: user opens a PR gets a reminder to look at the contributing guide, etc. Happy to update the README here to point at all other instances.

Happy to go with what you think best.

**Comment by joshmoore** [comment]
:+1: Merging so that:
 1. We can start to see how it looks in the GitHub UI when creating PRs, etc.
 2. So I can get https://github.com/zarr-developers/governance/pull/9 finalized.

**Comment by joshmoore** [comment]
e.g. creating an issue on the `community` repo which doesn't have either CoC or CONTRIB:
Screen Shot 2020-04-08 at 12 26 04
both link to `.github` whereas for zarr-python both link to the file in the current repo.

**Comment by alimanfoo** [comment]
Thanks @joshmoore :smile:

**Pull request merged**
